version: '3'

networks:
  diplom-network:
    name: diplom-network
    external: false

services:
  diplom-backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: unless-stopped

  migration-runner:
    build:
      context: .
      dockerfile: Dockerfile.migration-runner
    env_file:
      - .env