version: '3'

volumes:
  postgres_data:
  minio_data:

networks:
  diplom-network:
    name: diplom-network
    external: false

services:
  postgres:
    image: library/postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_DB: "Diplom"
    ports:
      - "5432:5432"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio-setup:
    build:
      context: .
      dockerfile: Dockerfile.minio-setup
    volumes:
      - ./minio-policy.json:/scripts/minio-policy.json
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    depends_on:
      minio:
        condition: service_healthy