version: '3'

volumes:
  postgres_data:
  minio_data:

networks:
  diplom-network:
    name: diplom-network
    external: false

services:
  postgres:
    image: library/postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_DB: "Diplom"
    ports:
      - "5432:5432"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped